Repository ruedap/alfred-font-awesome-workflow, pull requests merged in 2020-09, with the labels that each got.

#137 GitHub Actions
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/sync-labels.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test.yml
Labels: chore

#138 Refactor assets
  README.md
  screenshots/option-disable-pasting.png
  screenshots/screencast-illustrator.gif
  screenshots/screencast.gif
  screenshots/workflow.png
Labels: chore

#140 Divide styles in search results
  package-lock.json
  package.json
  src/arg.test.ts
  src/arg.ts
  src/assets/icons_object.test.ts
  src/assets/icons_object.ts
  src/icons.test.ts
  src/icons.ts
  src/index.ts
  src/put.test.ts
  src/put.ts
  src/query.ts
  src/search.test.ts
  tsconfig.json
  utils/converters/composite.ts
  utils/converters/svg_to_png.ts
  utils/experiments/index.html
Labels: feature

#144 Based on Font Awesome 5.14.0
  assets/info.plist
Labels: release

#145 Removing two dead links to quick.as
  README.md
Labels: docs
